services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
